#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Plucene
version:      1.20
version_from: 
installdirs:  site
requires:
    Time::Piece:                   1.08
    Class::Virtual:                0.03
    Lingua::Stem::En:              2.12
    IO::Handle:                    1.21_00
    List::Util:                    1.13
    File::Spec::Functions:         1.1
    Tie::Array::Sorted:            1.1
    Test::Harness:                 2.30
    Class::Accessor:               0.18
    Encode::compat:                0.05
    Bit::Vector::Minimal:          1.0
    Class::Accessor::Fast:         0.02
    IO::File:                      1.08
    Memoize:                       1.01
    File::Slurp:                   2002.1031
    IO::Scalar:                    2.104
    Carp:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
